[package]
name = "sudoku_cruncher"
version = "1.0.0"
authors = ["Hexeratops <bobby@derpybox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
